# Generated by Django 4.1.4 on 2022-12-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dep', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=20)),
            ],
        ),
    ]
