# Generated by Django 4.1.4 on 2022-12-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=100)),
                ('grade', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
